Revert: Update prepare_package.dart to use the process_runner package instead having duplicate code. #62710 (#63608)
This reverts #62710, since it has a noSuchMethodError in some circumstances.

This isn't just a straight git revert, because I had to resolve the conflicts in the reverted pubspec.yaml files and re-run flutter update-packages --force-upgrade to make the checksums match.